version: '3.8'

networks:
    nginx-php80-postgres-pgadmin:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php80-service
            - postgres
        networks:
            - nginx-php80-postgres-pgadmin

    # php
    php80-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php80-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php80-postgres-pgadmin

    postgres:
        image: postgres
        restart: always
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=symfonyProyect
        ports: 
            - 5432:5432
        networks:
            - nginx-php80-postgres-pgadmin

    pgadmin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "80:80"
        depends_on: 
            - postgres
        networks:
            - nginx-php80-postgres-pgadmin
